addons:
  ssh_known_hosts:
  - ssh.github.com
  - gist.github.com
  - github.com

language: python
python:
  - '2.7'
  
branches:
  only:
  - master

install:
  - pip install -r requirements.txt

script: 
  - mkdocs build
  
before_deploy:
- openssl aes-256-cbc -K $encrypted_f4e9782a8fc3_key -iv $encrypted_f4e9782a8fc3_iv -in super_secret.txt.enc -out deploy-key -d
- eval "$(ssh-agent -s)"
- chmod 600 deploy-key
- ssh-add deploy-key
- git remote add gh-token "git@github.com:hermitter/matrix-documentation.git";
- git fetch gh-token && git fetch gh-token gh-pages:gh-pages;

notifications:
  email: false

deploy:
  provider: script
  skip_cleanup: true
  script: if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then echo "Pushing to github"; PYTHONPATH=src/ mkdocs gh-deploy -v --clean --remote-name gh-token; git push gh-token gh-pages; fi;
  on:
    branch: master
