addons:
  ssh_known_hosts:
  - ssh.github.com
  - gist.github.com
  - github.com

language: python
python:
  - '2.7'

install:
  - pip install -r requirements.txt

script: 
  - mkdocs build
  
before_deploy:
- openssl aes-256-cbc -K $encrypted_f4e9782a8fc3_key -iv $encrypted_f4e9782a8fc3_iv -in super_secret.txt.enc -out /tmp/super_secret.txt -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/super_secret.txt
- ssh-add /tmp/super_secret.txt
- git config user.name "Hermitter"
- git config user.email "chacin.carlos9798@gmail.com"
- git remote add gh-token "git@github.com:hermitter/matrix-documentation.git";

notifications:
  email: false

deploy:
  provider: script
  skip_cleanup: true
  script: git fetch gh-token && git fetch gh-token gh-pages:gh-pages;
  on:
    branch: master