addons:
  ssh_known_hosts:
  - ssh.github.com
  - gist.github.com
  - github.com

language: python
python:
  - '2.7'

install:
  - pip install -r requirements.txt

script: 
  - mkdocs build
  - echo | ls $TRAVIS_BUILD_DIR/site
  
before_deploy:
- openssl aes-256-cbc -K $encrypted_f4e9782a8fc3_key -iv $encrypted_f4e9782a8fc3_iv -in super_secret.txt.enc -out /tmp/super_secret.txt -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/super_secret.txt
- ssh-add /tmp/super_secret.txt

notifications:
  email: false

deploy:
  provider: script
  skip_cleanup: true
  script: git push origin gh-pages -f 
  on:
    branch: master