language: python

python:
  - '2.7'

install:
  - pip install -r requirements.txt

# script: 
#   - mkdocs build

notifications:
  email: false

  script: ls

deploy:
  provider: script
  skip-cleanup: true
  script: ./deploy.sh
  on:
    branch: master