before_install:
  - openssl aes-256-cbc -K $encrypted_f4e9782a8fc3_key -iv $encrypted_f4e9782a8fc3_iv -in super_secret.txt.enc -out super_secret.txt -d

language: python
python:
  - "2.7"
  
install:
  - pip install -r requirements.txt

deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  local-dir: ./site
  on:
    branch: master