language: python
python:
- '2.7'
before_deploy:
- openssl aes-256-cbc -K $encrypted_f4e9782a8fc3_key -iv $encrypted_f4e9782a8fc3_iv
  -in super_secret.txt.enc -out /tmp/super_secret.txt -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/super_secret.txt
- ssh-add /tmp/super_secret.txt
install:
- pip install -r requirements.txt
notifications:
  email: false
script: mkdocs build
deploy:
  provider: pages
  skip-cleanup: true
  local-dir: deploy.sh
  on:
    branch: master
env:
  global:
    secure: PE/PRgnUs8Au2Sr7Au+AusFhwX6Ylzkwf2ers2IPh6a3+0IH7CF0/8hY38ewaYadtOAlYGC8PZtydM2QkgfyKe4peOPmsL2mDICDIqcstiyuij5P8B2taUF4AUBQif0m09WKE81zx3iiS3+eDOHxBDHTtNTlFpxeCC8vuMkC+fGPiULok5KIF0nOz7Tu+U7pCv6R+ukfrU8hu9G9/8v0yWK3x6Scn5R3Couxx7vR8rAIiYZ10DWB1dFlg5xQaceXum0cwtCTp0FD5G7xxUBDHjmZdkjTUT0eLlitX5iZv5EXk5KMn9TqmmfswxyQOSUVMkfcuKYoQ6jMmaLJQ/95CcDHqVg5WzFfwE7WD74UVXzIEpHFXiUJu8uXt17jfKCvIHO/DOFKXlPzc9ouBZCogV4++O7LsyMsuKRauwRRTeRp4qcdXFZR5MBtMf7nQ15ORXBDlKV+Gk6PL1WW0iPpO62nHcM455xlAbWrMeioKmPguriaqAQTUYOVyRvscnzfdJU3QX4tOtSLgqWRC2O/iDa+2tOyB6GvDm92Ju0cIpbdKf0JJRnxy1RyCgOu8DUZmbGCOLymZfWy6it1exc6cRQVx7sukphQ4/L5DQQebbviij/yPuEbxLyZazBMg1f5FrH7MH9M3cjRoWhJ6/0eQKNbYQe1jTXUUQsv8UDz9H4=
