# addons:
#   ssh_known_hosts: <deploy-host>

before_deploy:
  - openssl aes-256-cbc -K $encrypted_f4e9782a8fc3_key -iv $encrypted_f4e9782a8fc3_iv -in super_secret.txt.enc -out super_secret.txt -d
  - eval "$(ssh-agent -s)"
  - chmod 600 super_secret.txt
  - ssh-add super_secret.txt

language: python
python:
  - "2.7"

install:
  - pip install -r requirements.txt

# Don't email me the results of the test runs.
notifications:
  email: false

script: mkdocs build

deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  local-dir: ./site
  on:
    branch: master