language: python
python:
  - "2.7"

before_install:
  - openssl aes-256-cbc -K $encrypted_f4e9782a8fc3_key -iv $encrypted_f4e9782a8fc3_iv -in super_secret.txt.enc -out super_secret.txt -d

install:
  - pip install -r requirements.txt

# Don't email me the results of the test runs.
notifications:
  email: false

script: 
  - mkdocs build --clean

after_success:
  # Add the ssh key
  - eval "$(ssh-agent)"
  - chmod 600 id_rsa
  - ssh-add id_rsa

deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  local-dir: site
  on:
    branch: master
